gmaps:
  apiKey: ${GMAPS_APIKEY}
server:
  port: 8085
spring:
  profiles:
    active: demo
  datasource:
    url: jdbc:mysql://localhost:3302/geoadvisor?useSSL=false&allowPublicKeyRetrieval=true
    username: geoadvisor
    password: geoadvisor
    driver-class-name: com.mysql.cj.jdbc.Driver
  # show SQL
  jpa:
    show-sql: false
    # DDL generation
    hibernate:
      ddl-auto: create
