version: "3.8"

services:
  mysql:
    container_name: geoadvisor-mysql-db
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    restart: on-failure
    ports:
      - "3302:3306"
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d
      - geoadvisor-mysql-data:/var/lib/mysql

volumes:
  geoadvisor-mysql-data:
